Repository theforeman/puppet-candlepin, pull requests merged in 2020-04, with the labels that each got.

#149 Allow extlib 5.x
  metadata.json
Labels: Needs testing, Not yet reviewed

#148 Fixes #29194 - Support EL8
  .sync.yml
  .travis.yml
  Gemfile
  examples/basic_candlepin.pp
  metadata.json
  spec/classes/candlepin_spec.rb
  spec/spec_helper_acceptance.rb
Labels: Enhancement, Needs testing, Not yet reviewed

#150 Drop EPEL in the acceptance tests
  .sync.yml
  spec/spec_helper_acceptance.rb
Labels: Needs testing, Not yet reviewed

#143 Fixes #28924: Drop qpid queue and add exposing of Artemis
  .fixtures.yml
  files/tomcat/cert-roles.properties
  files/tomcat/jaas.conf
  files/tomcat/login.config
  manifests/artemis.pp
  manifests/init.pp
  manifests/params.pp
  manifests/qpid.pp
  metadata.json
  spec/acceptance/basic_candlepin_spec.rb
  spec/classes/candlepin_spec.rb
  templates/broker.xml.erb
  templates/candlepin.conf.erb
  templates/tomcat/cert-users.properties.erb
Labels: Backwards incompatible, Needs testing, Not yet reviewed

#152 Fixes #29625 - Stop accepting TLS 1.1 connections
  manifests/params.pp
Labels: Backwards incompatible, Needs testing, Not yet reviewed
