Repository theforeman/puppet-candlepin, pull requests merged in 2021-06, with the labels that each got.

#178 Support Puppet 7
  .github/workflows/ci.yml
  metadata.json
Labels: Needs testing, Not yet reviewed

#202 Bump version to 12.0.0
  metadata.json
Labels: Needs testing, Not yet reviewed, skip-changelog

#200 Drop Puppet 5
  metadata.json
Labels: Needs testing, Not yet reviewed

#199 Refs #32585: Support artemis_client_dn as a Deferred object
  examples/basic_candlepin.pp
  manifests/artemis.pp
  manifests/init.pp
  spec/acceptance/basic_candlepin_spec.rb
  spec/classes/candlepin_spec.rb
  templates/tomcat/cert-users.properties.erb
Labels: Enhancement, Needs testing, Not yet reviewed
