Repository theforeman/puppet-candlepin, pull requests merged in 2021-04, with the labels that each got.

#181 Add user and group parameters
  manifests/artemis.pp
  manifests/config.pp
  manifests/init.pp
  manifests/params.pp
Labels: Enhancement, Needs testing, Not yet reviewed

#180 Update yumrepo to use yum.theforeman.org
  manifests/repo.pp
  spec/classes/repo_spec.rb
  spec/setup_acceptance_node.pp
Labels: Enhancement, Needs testing, Not yet reviewed

#182 Add static defaults for parameters
  manifests/init.pp
  manifests/params.pp
Labels: Needs testing, Not yet reviewed

#183 Tomcat parameter is named sslProtocol not sslProtocols
  spec/classes/candlepin_spec.rb
  templates/tomcat/server.xml.erb
Labels: Bug, Needs testing, Not yet reviewed

#179 Drop unknown Tomcat properties
  templates/tomcat/server.xml.erb
Labels: Enhancement, Needs testing, Not yet reviewed

#186 Manage the candlepin::group
  examples/basic_candlepin.pp
  manifests/config.pp
  spec/classes/candlepin_spec.rb
Labels: Enhancement, Needs testing, Not yet reviewed

#192 Release 11.3.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, Not yet reviewed, skip-changelog
