Repository theforeman/puppet-candlepin, pull requests merged in 2021-01, with the labels that each got.

#169 Refs #31346 - Expose java_package parameter
  manifests/init.pp
  manifests/install.pp
  spec/classes/candlepin_spec.rb
Labels: Enhancement, Needs testing, Not yet reviewed

#172 Fixes #31607 - Increase Artemis disk usage limit
  templates/broker.xml.erb
Labels: Enhancement, Needs testing

#171 Release 11.1.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, Not yet reviewed, skip-changelog
