Repository theforeman/puppet-candlepin, pull requests merged in 2021-02, with the labels that each got.

#174 Candlepin package in Katello nightly repositories now requires Java 11
  examples/basic_candlepin.pp
Labels: Needs testing, Not yet reviewed

#173 Drop dependency on puppet-selinux
  .fixtures.yml
  manifests/artemis.pp
  metadata.json
Labels: Needs testing, Not yet reviewed

#175 Enable pki-core module on EL8
  manifests/install.pp
  metadata.json
  spec/classes/candlepin_spec.rb
  spec/setup_acceptance_node.pp
Labels: Enhancement

#176 Release 11.2.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, Not yet reviewed, skip-changelog
