Repository theforeman/puppet-candlepin, pull requests merged in 2021-08, with the labels that each got.

#204 Fix beaker task
  .github/workflows/ci.yml
  Gemfile
  Rakefile
  spec/spec_helper_acceptance.rb
Labels: Modulesync, Needs testing, Not yet reviewed

#205 Fixes #33321 - Update job scheduling config options for correctness
  spec/classes/candlepin_spec.rb
  templates/candlepin.conf.erb
Labels: Bug

#206 Release 12.0.1
  CHANGELOG.md
  metadata.json
Labels: Needs testing, Not yet reviewed, skip-changelog
