Repository theforeman/puppet-candlepin, pull requests merged in 2022-01, with the labels that each got.

#212 Pin rdoc to < 6.4
  Gemfile
Labels: Needs testing, Not yet reviewed, skip-changelog

#213 Fixes #30366 - Candlepin config file owned by root
  manifests/config.pp
Labels: Needs testing, Not yet reviewed

#211 Disable FIPS support within Tomcat Java environment
  manifests/init.pp
  spec/classes/candlepin_spec.rb
  templates/tomcat/tomcat.conf.erb
Labels: Enhancement, Needs testing, Not yet reviewed
