Repository theforeman/puppet-candlepin, pull requests merged in 2023-11, with the labels that each got.

#241 Update gems to support testing Puppet 8
  .github/workflows/ci.yml
  .gitignore
  CONTRIBUTING.md
  Gemfile
Labels: Modulesync

#246 Mark compatible with puppet-extlib 7.x
  metadata.json
Labels: Enhancement, Not yet reviewed

#190 Pre-create some tomcat config files in selinux enabled acceptance tests
  spec/setup_acceptance_node.pp
Labels: Needs testing

#248 Mark compatible with puppetlabs/postgresql 10.x
  metadata.json
Labels: Enhancement

#247 Release 15.0.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog
