Repository theforeman/puppet-candlepin, pull requests merged in 2024-05, with the labels that each got.

#259 Support Candlepin 4.4
  .github/workflows/ci.yml
  .sync.yml
  README.md
  lib/puppet/provider/cpdb_create/cpdb_create.rb
  lib/puppet/provider/cpdb_update/cpdb_update.rb
  lib/puppet/type/cpdb_create.rb
  manifests/config.pp
  manifests/database/postgresql.pp
  manifests/init.pp
  spec/classes/candlepin_spec.rb
  templates/candlepin.conf.epp
Labels: Backwards incompatible

#261 Release 16.0.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog

#262 Add candlepin.consumer.facts.match_regex parameter to candlepin class
  manifests/config.pp
  manifests/init.pp
  spec/classes/candlepin_spec.rb
  templates/candlepin.conf.epp
Labels: Enhancement
